<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-01H70DH" failures="1" tests="4" name="com.crm.OrganizationTests.POMcreateOrgTest" time="104.948" errors="0" timestamp="2022-03-16T17:06:46 IST" skipped="3">
  <testcase classname="com.crm.OrganizationTests.POMcreateOrgTest" name="createOrgTest" time="26.334">
    <skipped/>
  </testcase> <!-- createOrgTest -->
  <system-out>
    <![CDATA[createOrgTest-----Testscripts execution started
createOrgTest-----Testscripts Skipped]]>
  </system-out>
  <testcase classname="com.crm.OrganizationTests.POMcreateOrgTest" name="createOrgTest" time="20.460">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.crm.OrganizationTests.POMcreateOrgTest.createOrgTest(POMcreateOrgTest.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrgTest -->
  <system-out>
    <![CDATA[createOrgTest-----Testscripts execution started
createOrgTest------Testscripts Failed]]>
  </system-out>
  <testcase classname="com.crm.OrganizationTests.POMcreateOrgTest" name="createOrgTest" time="32.813">
    <skipped/>
  </testcase> <!-- createOrgTest -->
  <system-out>
    <![CDATA[createOrgTest-----Testscripts execution started
createOrgTest-----Testscripts Skipped]]>
  </system-out>
  <testcase classname="com.crm.OrganizationTests.POMcreateOrgTest" name="createOrgTest" time="25.341">
    <skipped/>
  </testcase> <!-- createOrgTest -->
  <system-out>
    <![CDATA[createOrgTest-----Testscripts execution started
createOrgTest-----Testscripts Skipped]]>
  </system-out>
</testsuite> <!-- com.crm.OrganizationTests.POMcreateOrgTest -->
